# Generated by Django 5.1 on 2024-08-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
