# Generated by Django 5.1 on 2024-08-27 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_rename_owner_stream_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='discount',
            field=models.FloatField(),
        ),
    ]
