# Generated by Django 5.1 on 2024-08-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0009_sitesettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stream',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
