# Generated by Django 5.1 on 2024-08-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0010_remove_order_stream_remove_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
